[tool.poetry]
name = "..."
version = "0.1.0"
description = "..."
authors = ["Ben Felder <...@...>"]
license = "MIT"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.12"
typer = "*"
loguru = "*"

[tool.poetry.group.dev.dependencies]
ruff = "*"
pyright = "*"
deptry = "*"
vulture = "*"
commitizen = "*"

[tool.poetry.group.test.dependencies]
pytest = "*"
pytest-cov = "*"

[tool.poetry.scripts]
app = "app.__main__:cli"

[tool.ruff]
# https://docs.astral.sh/ruff/settings/
line-length = 88
target-version = "py312"
ignore = ["E402", "F841", "F401"]
src = ["app"]

[tool.ruff.isort]
known-first-party = ["app", "tests"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.commitizen]
# Set major_version_zero to false to move to 1.0.0
major_version_zero = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
