# https://python-poetry.org/docs/pyproject/
[tool.poetry]
name = "..."
version = "0.1.0"
description = "..."
authors = ["Ben Felder <...@...>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.12"
typer = "*"
loguru = "*"

[tool.poetry.group.dev.dependencies]
ruff = "*"
pyright = "*"
deptry = "*"
vulture = "*"
commitizen = "*"

[tool.poetry.group.test.dependencies]
pytest = "*"
pytest-cov = "*"

[tool.poetry.scripts]
app = "app.__main__:cli"

[tool.ruff]
# https://docs.astral.sh/ruff/settings/
src = ["app"]
target-version = "py312"
line-length = 88
fix = true
ignore = ["E402", "F841"]
extend-select = ["T100", "T201"]
extend-unsafe-fixes = ["F401"]

[tool.ruff.lint.mccabe]
max-complexity = 5

[tool.ruff.lint.isort]
lines-after-imports = 2
known-first-party = ["app", "tests"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.commitizen]
# Set major_version_zero to false to move to 1.0.0
major_version_zero = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
